### ISSUE TITLE
Add guide for going from REST -> Lighthouse

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse-docs#12]
This would be helpful for users that are coming from a REST background or are migrating an existing REST api.

**Comment by ctf0** [comment]
@spawnia any updates on this ?

**Comment by spawnia** [comment]
Nope, working on a v2.3 release and on documenting that. Feel free to write up something yourself and submit a PR.

**Comment by spawnia** [comment]
I am still open if someone else wants to write something up about this, but feel it is out of scope for this library. Docs are moving to https://github.com/nuwave/lighthouse btw.
