### ISSUE TITLE
Document the namespace functionality of @group

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse-docs#13]

**Comment by ctf0** [comment]
it seems its already added but not published yet https://github.com/nuwave/lighthouse-docs/blob/master/docs/directives-nodes.md#group

**Comment by spawnia** [comment]
Right, good catch. @chrissm79 Should this be in the `v2.1` docs as well?

**Comment by chrissm79** [comment]
@ctf0 Good catch indeed! @spawnia yeah, this one would indeed be part of the `v2.1` docs
