### ISSUE TITLE
add a search functionality

### ISSUE THREAD

**Issue by ctf0** [nuwave/lighthouse-docs#16]

**Comment by spawnia** [comment]
Like a global full-text search?

**Comment by ctf0** [comment]
for a start could be a simple search for directives, later we can use the full text when the docs are ready

**Comment by chrissm79** [comment]
I'll add Algolia to the docs: https://docusaurus.io/docs/en/search#extra-search-options

**Comment by ctf0** [comment]
@chrissm79 even better

**Comment by spawnia** [comment]
Search is coming to the new docs over at https://github.com/nuwave/lighthouse
