### ISSUE TITLE
merge directives into one page

### ISSUE THREAD

**Issue by ctf0** [nuwave/lighthouse-docs#17]
this way you dont have to go back & forth between all the items to find what u r after, especially that the pages are not loaded vie `pjax or a js router` which means all the assets need to be reloaded on each section u visit.

**Comment by spawnia** [comment]
I am worried that the list is going to get super long. Also, i think it might make it hard to find a directive for a specific use case.

However, i am a bit surprised that the pages take so long to load and do not seem to be cached. Switching between the sections certainly feels sluggish.

**Comment by ctf0** [comment]
not really, check lodash docs, all the api methods are listed in the sidebar under different cats, using search simply filters the list

**Comment by spawnia** [comment]
Resolved by #22 as part of the v2.2 docs

**Comment by ctf0** [comment]
@spawnia awesome job, btw it could be easier if u listed it on the sidebar with separate categories

**Comment by spawnia** [comment]
It is hard to categorise directives, since some of them have many use-cases. I chose to go for a simple alphabetical listing and plan to add comprehensive guides that deal with a certain aspect of directives.
