### ISSUE TITLE
Web GraphQL IDE: provide links/options on how to install them

### ISSUE THREAD

**Issue by mfn** [nuwave/lighthouse-docs#19]
See https://github.com/nuwave/lighthouse/issues/219

It would be great if from the start a new user has an idea what is available (e.g. https://github.com/mll-lab/laravel-graphql-playground as mentioned in https://github.com/nuwave/lighthouse/issues/219#issuecomment-406215016 ).

**Comment by mfn** [comment]
Looking at https://lighthouse-php.netlify.com/docs/installation.html I think a separate page would be a better fit (as to not go unnoticed because it's at the end of the page).

But then again, a dedicated page for something not a part of this package probably feels strange. But if the common sense is that it's a often requested feature, it might make sense. 🤷‍♀️

**Comment by spawnia** [comment]
Hm good point. How about we do a section like "Daily Usage" where we put in Tips/Tricks around development ergonomics?

**Comment by mfn** [comment]
Sounds good to me!

**Comment by hailwood** [comment]
Another option I like to promote if users don't want to add one to their install, but still want to be able to query their graphql endpoint is Altair https://altair.sirmuel.design/

![image](https://user-images.githubusercontent.com/709773/42970524-a03a8e82-8bfd-11e8-9709-2c6d06e30bd0.png)

**Comment by imolorhe** [comment]
Looking at https://github.com/mll-lab/laravel-graphql-playground, I think it should be pretty easy to add support for Altair in PHP, especially as all the required files are available at https://www.jsdelivr.com/package/npm/altair-static?path=build%2Fdist 🙂

**Comment by spawnia** [comment]
@imolorhe feel free to add it to the docs, the are now managed in https://github.com/nuwave/lighthouse
