### ISSUE TITLE
This project needs a domain

### ISSUE THREAD

**Issue by kikoseijo** [nuwave/lighthouse-docs#4]
What you think @hailwood ? upvotes?

**Comment by kikoseijo** [comment]
You going to rock with this library for so long...
I think it deserves a domain name, maybe http://lighthose.nuwave.com?¿

**Comment by hailwood** [comment]
Yeah that's decently easy to remember compared to the current docs domain. It all depends on whether @chrissm79 &co are ok with having it off the company website.

Otherwise can gatsby sites be hosted on github pages?  http://graphql-lighthouse.github.io/ or similar could work.

**Comment by chrissm79** [comment]
@hailwood @kikoseijo Was considering this right off the bat but just wanted to get the docs up and running so I went the free/easy route 😄

Netlify allows users to use custom domains so I just need to find an easy to remember one. I secured the domain `lighthouse-php.com`... unless I think of a better one this will probably be the direction I go in. My company domain is `nuwavecommerce.com`, and I would've preferred the `lighthouse.nuwave.com` domain but unfortunately I don't own it :-/

**Comment by olivernybroe** [comment]
@chrissm79 What about nuwave.io as that is free? Then use the .io domain for open-source stuff and your .com domain for your private stuff.

**Comment by spawnia** [comment]
What is the status on this? `lighthouse-php.com` would indeed be very nice to have as a domain? AFAIK, netlify allows you to add custom domains https://www.netlify.com/docs/custom-domains/

I would be willing to chip in for the Registrar fees.

**Comment by spawnia** [comment]
It is done https://lighthouse-php.com/
