### ISSUE TITLE
[Feature] Provide a CHANGELOG between versions

### ISSUE THREAD

**Issue by robsontenorio** [nuwave/lighthouse-docs#72]
This is a good way for non package developers keep tracking of improvements between versions. 

Making a diff on master branch from main package can be painful.

**Comment by robsontenorio** [comment]
Or some release notes when tagging a branch

Ex: 
https://github.com/nuxt/nuxt.js/releases

**Comment by spawnia** [comment]
For now, some hand-written release notes are put in the releases. Has not been too much work so we can just do it that way for now. Feel free to reopen in the main repo if you have a suggestion for how to automate this.
