### ISSUE TITLE
Documentation page 404

### ISSUE THREAD

**Issue by yanzhen0610** [nuwave/lighthouse-docs#91]
**Related Issue/PR from the main repo**

Link to related Issue/PR this PR corresponds to

**Lighthouse Version**

Which version of Lighthouse does this apply to?

[https://lighthouse-php.com/](https://lighthouse-php.com/) -> [https://lighthouse-php.com/4.11/getting-started/installation.html](https://lighthouse-php.com/4.11/getting-started/installation.html)

It's showing 404 if I go to the page by right click and hit open in new tab from the main page.

Browser: Google Chrome Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by spawnia** [comment]
Can you please reopen this in the main repository?
